version: "3.8"

services:
  app:
    build: .
    container_name: task-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://mohamed10:Mohamed10@cluster0.uvbpqsf.mongodb.net/
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=7d

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: